//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerczegKristofFejlabuak.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class species
    {
        public string species_name { get; set; }
        public Nullable<short> felfedezes { get; set; }
        public string megjelenes { get; set; }
        public string genus_name { get; set; }
        public string atlagos_meret { get; set; }
        public string legnagyobb_meret { get; set; }
        public Nullable<byte> cute { get; set; }
    
        public virtual classification classification { get; set; }
    }
}
