//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerczegKristofFejlabuak.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class subclass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subclass()
        {
            this.classification = new HashSet<classification>();
        }
    
        public string subclass_name { get; set; }
        public Nullable<int> belso_szavazas_eredmenye { get; set; }
        public Nullable<short> megtalalas_eve { get; set; }
        public Nullable<byte> external_shell { get; set; }
        public Nullable<byte> kihalt { get; set; }
        public string megjelenes_idoszaka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<classification> classification { get; set; }
    }
}
